// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_fbv9-xDJfFVw8l0GhqnG4rA-szpqac',
    appId: '1:1043767445670:web:aaaa8f90735f1d97284c67',
    messagingSenderId: '1043767445670',
    projectId: 'giftgenie-d5c72',
    authDomain: 'giftgenie-d5c72.firebaseapp.com',
    storageBucket: 'giftgenie-d5c72.firebasestorage.app',
    measurementId: 'G-Z0V0XLXB27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVgF35DXMAQ5ShnAWsXDadUtJ-DEtyok',
    appId: '1:1043767445670:android:2088ea4eb6d83b09284c67',
    messagingSenderId: '1043767445670',
    projectId: 'giftgenie-d5c72',
    storageBucket: 'giftgenie-d5c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW63btsiaBBXzRLNgw01AfWir0FH2ZWr4',
    appId: '1:1043767445670:ios:c6984b3f4cd512e1284c67',
    messagingSenderId: '1043767445670',
    projectId: 'giftgenie-d5c72',
    storageBucket: 'giftgenie-d5c72.firebasestorage.app',
    iosBundleId: 'com.example.giftgenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW63btsiaBBXzRLNgw01AfWir0FH2ZWr4',
    appId: '1:1043767445670:ios:c6984b3f4cd512e1284c67',
    messagingSenderId: '1043767445670',
    projectId: 'giftgenie-d5c72',
    storageBucket: 'giftgenie-d5c72.firebasestorage.app',
    iosBundleId: 'com.example.giftgenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9_fbv9-xDJfFVw8l0GhqnG4rA-szpqac',
    appId: '1:1043767445670:web:634d1044a015ce05284c67',
    messagingSenderId: '1043767445670',
    projectId: 'giftgenie-d5c72',
    authDomain: 'giftgenie-d5c72.firebaseapp.com',
    storageBucket: 'giftgenie-d5c72.firebasestorage.app',
    measurementId: 'G-K2LV51CLSV',
  );
}
